server:
  port: 8083

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/co-admin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:log4jdbc:mysql://localhost:3306/co-admin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
    #    使用log4jdbc
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      test-while-idle: true
      validation-query: select 1
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: admin
        login-password: admin
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  output:
    ansi:
      enabled: always
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 5000
#  data:
#    redis:
#      repositories:
#        enabled: false

  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: none

#    properties:
#      hibernate.format_sql: true
#      hibernate.use_sql_comments: true

snow:
  flake:
    id:
      data: 1
      machine: 1

#log4jdbc:
#  spylogdelegator:
#    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
#    drivers: com.mysql.cj.jdbc.Driver
#    auto:
#      load:
#        popular:
#          drivers: false

#logging:
#  level:
#    org:
#      springframework:
#        security: debug
#      hibernate: debug