server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/co-admin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: admin
        login-password: admin
        enabled: true
        url-pattern: /druid/*
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 5000

